POST https://node-do-zero-t4h2.onrender.com/videos
Content-type: application/json

{
    "title": "Video exclusao",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://node-do-zero-t4h2.onrender.com/videos

###

PUT https://node-do-zero-t4h2.onrender.com/videos/9a1c32ef-2e76-441c-b290-9a46ea9bef9f
Content-type: application/json

{
    "title": "Video node Atualizado",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE https://node-do-zero-t4h2.onrender.com/videos/fdf6c7b1-ed12-4d71-8bb2-9cce26b7972a
